backend:
  name: github
  branch: main

media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "ids"
    label: "Free Fire IDs"
    folder: "content/ids"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "ID Title / Header", name: "title", widget: "string"}
      - {label: "Level Tag (e.g., Level 72)", name: "level", widget: "string", required: false}
      - {label: "Image Size Style", name: "img_size", widget: "select", options: ["nom", "big", "tall", "bag"], default: "nom"}
      - {label: "ID Screenshot / Image", name: "image", widget: "image"}
      - {label: "Selling Price (Rs.)", name: "price", widget: "string"}
      - {label: "Original Cut Price (Rs.)", name: "original_price", widget: "string", required: false}
      - {label: "Details / Features", name: "details", widget: "text"}
      - {label: "WhatsApp Number", name: "whatsapp_num", widget: "string", default: "923132478759", required: false}
      - {label: "Buy Button Message Text", name: "buy_text", widget: "string", default: "Mujhe ID buy karni hai", required: false}
      
